inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ClassLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  IgnoreCopDirectives: true
  Exclude:
    - "**/*_spec.rb"

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 6